export const tasksActions = {
  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
  CREATE_TASK_ERROR: 'CREATE_TASK_ERROR',
  DELETE_TASK: 'DELETE_TASK',
  DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
  DELETE_TASK_ERROR: 'DELETE_TASK_ERROR',
  EDIT_TASK: 'EDIT_TASK',
  EDIT_TASK_SUCCESS: 'EDIT_TASK_SUCCES',
  EDIT_TASK_ERROR: 'EDIT_TASK_ERROR',
  GET_ALL: 'GET_ALL',
  GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
  GET_ALL_ERROR: 'GET_ALL_ERROR',
  GET_ONE: 'GET_ONE',
  GET_ONE_SUCCESS: 'GET_ONE_SUCCESS',
  GET_ONE_ERROR: 'GET_ONE_ERROR',
  CLEAR_CURRENT: 'CLEAR_CURRENT'
}